<div class="corpo">
	<div class="centro">
		<h1>Contato</h1>
		Gostaríamos muito de receber seus comentários e dúvidas sobre nosso sistema!
		<br>
		<Br>
		<form id="form_contato" name="contato" method="post" action="envio.html">
				<fieldset>
					<legend style="font-size:12px; color:#363636" width="96%">Entre em contato conosco!</legend>
					<p> 
						Nome: <br />
						<input name="nome" type="text" id="user_nome" size="35" maxlength="30" />
					</p>
					<p>
						Telefone: <br/>
						<input name="telefone" type="text" id="user_tel" size="35" maxlength="30" />
					</p>

					<p>
						E-mail: <br/>
						<input name="email" type="text" id="user_mail" size="35" maxlength="30" />
					</p>		
												<p>
						Mensagem <br/>
						<textarea name="mensagem" id="user_msg" cols="50" rows="6"> </textarea>
					</p>
					<p>
						<input type="submit" name="enviar" id="btn_enviar" value="Enviar" />
					</p>
				</fieldset>
			
			</form>
	</div>
</div>