<div class="corpo">
	<div class="centro">
		<h1>Quem Somos</h1>
		<br>
		<p class="paragrafo"> 
			AVALIZZA  é  uma  Empresa  de apoio comercial  que, com  ferramentas  e 
			tecnologias  auxiliam  no  processo  de  avaliação  e  cadastro,  facilitando  e 
			reduzindo o tempo de espera para a aprovação e liberação de crédito.  
		</p>  
		<p class="paragrafo">
			Propomos deixar pronto o cadastro dos novos clientes com base 
			nas informações comerciais de outros fornecedores, evitando algumas situações 
			desconfortáveis. 
		</p>
		<p class="paragrafo">
			Nossa empresa foi  projetada  com  estrutura  tecnológica  avançada  para 
			oferecer  um  serviço  de  qualidade,  rapidez  e  segurança  na  transmissão  e 
			recepção de dados, onde são gerados e armazenados com total segurança.
		</p>
		<p class="paragrafo">
		<p class="paragrafo">
			Acreditamos que, com a parceria entre Fornecedor x Revendedor 
			eliminará fraudes e golpes aplicados por pessoas mal-intencionadas.</p>
		<hR>
		<h3>MISSÃO</h3>
		<p class="paragrafo"> 
			Oferecer  através  de  nossas  ferramentas  praticidade  e  comodidade  aos 
			usuários, otimizar a cada dia o processo de cadastro, para efetivação de compra 
			e venda, maximizando os resultados para todas as partes.
		</P>
		
		<hr>
		<h3>VISÃO</h3>
		<p class="paragrafo"> 
			Ser a empresa líder na prestação do serviço, ser reconhecida e respeitada 
			pelo  público  nacional  e  internacional,  sem  perder  a  essência  de 
			empreendedorismo.
		</P>
	</div>
</div>